version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.base.dockerfile
      target: base
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./templates:/app/templates
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload